mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('thoughts/list', views.ThoughtView.as_view(), name='thoughts'),
    path('thoughts/', views.ThinkView, name='think'),
    path('thoughts/think', views.think, name='thinking'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Thought(models.Model):
    title = models.CharField(max_length=200)
    thought_text = models.CharField(max_length=200)
    def __str__(self):
        return self.title

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import json
from .models import Question, Choice, Thought

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

class ThoughtView(generic.ListView):
    template_name = 'polls/thoughts.html'
    context_object_name = 'latest_thought_list'
    
    def get_queryset(self):
        return Thought.objects.order_by()

def ThinkView(request):
    return render(request, 'polls/think.html')

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def think(request):
    t = Thought(title=request.POST.get('title'), thought_text=request.POST.get('thought_text'))
    t.save()
    return HttpResponseRedirect(reverse('polls:thoughts'))

polls/templates/polls/detail.html
<head>
    <title>Details</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Kanadaka&display=swap" rel="stylesheet">
</head>
<h1><a href="{% url 'polls:index' %}">Polls</a> -> {{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<div class="form-check">
    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label class="form-check-label" for="choice{{ forloop.counter }}">
        {{ choice.choice_text }}
    </label>
</div>
{% endfor %}
<div class='form-check'><input type="submit" value="Vote"></div>
</form>
<footer>
    <p>Author: Kabir Menghrajani</p>
    <p><a href="mailto:km5qte@virginia.edu">km5qte@virginia.edu</a></p>
</footer>
<style>
    body{
        background-color: aquamarine;
    }
    h1{
        color: navy;
        text-align: center;
        font-size: xx-large;
        font-family: 'Akaya Kanadaka', cursive;
    }
    .form-check, p{
        color: navy;
        text-align: center;
        font-size: x-large;
        font-family: 'Akaya Kanadaka', cursive;
        list-style-position: inside;
    }
    footer{
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>

polls/templates/polls/index.html
<head>
    <title>Polls</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Kanadaka&display=swap" rel="stylesheet">
</head>
<h2>Available polls:</h2>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<footer>
    <p>Author: Kabir Menghrajani</p>
    <p><a href="mailto:km5qte@virginia.edu">km5qte@virginia.edu</a></p>
</footer>
<style>
    body{
        background-color: aquamarine;
    }
    h2{
        color: navy;
        text-align: center;
        font-size: xx-large;
        font-family: 'Akaya Kanadaka', cursive;
    }
    li, footer, p{
        color: navy;
        text-align: center;
        font-size: x-large;
        font-family: 'Akaya Kanadaka', cursive;
        list-style-position: inside;
    }
    li{
        margin-left: -50px;
    }

    .blank-space{
        height: 50px;
    }
    footer{
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>

polls/templates/polls/results.html
<head>
    <title>Results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Kanadaka&display=swap" rel="stylesheet">
</head>
<h1><a href="{% url 'polls:index' %}">Polls</a> -> <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> -> Results</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<p><a href="{% url 'polls:detail' question.id %}">Vote again?</a></p>
<footer>
    <p>Author: Kabir Menghrajani</p>
    <p><a href="mailto:km5qte@virginia.edu">km5qte@virginia.edu</a></p>
</footer>
<style>
    body{
        background-color: aquamarine;
    }
    h1{
        color: navy;
        text-align: center;
        font-size: xx-large;
        font-family: 'Akaya Kanadaka', cursive;
    }
    li, p, footer{
        color: navy;
        text-align: center;
        font-size: x-large;
        font-family: 'Akaya Kanadaka', cursive;
        list-style-position: inside;
    }
    li{
        margin-left: -50px;
    }
    footer{
        position: absolute;
        bottom: 0;
        width: 100%;
    }
    .blank-space{
        height: 50px;
    }
</style>

polls/templates/polls/think.html
<head>
    <title>Submit a Thought</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Kanadaka&display=swap" rel="stylesheet">
</head>
<div class="blank-space"></div>
<form action="{% url 'polls:thinking' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="key">Enter your thought title.</label>
        <textarea class="form-control" id="key" rows="1" name="title"></textarea>
    </div>
    <div class="blank-space"></div>
    <div class="form-group">
        <label for="val">Whats on your mind?</label>
        <textarea class="form-control" id="val" rows="5" name="thought_text"></textarea>
    </div>
    <div class="blank-space"></div>
    <div class="form-group">
        <input type="submit" value="Think">
    </div>
</form>
<footer>
    <p>Author: Kabir Menghrajani</p>
    <p><a href="mailto:km5qte@virginia.edu">km5qte@virginia.edu</a></p>
</footer>
<style>
    body{
        background-color: aquamarine;
    }
    .form-group, footer{
        color: navy;
        text-align: center;
        font-size: xx-large;
        font-family: 'Akaya Kanadaka', cursive;
    }
    .blank-space{
        height: 50px;
    }
    footer{
        font-size: x-large;
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>

polls/templates/polls/thoughts.html
<head>
    <title>Thoughts</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Kanadaka&display=swap" rel="stylesheet">
</head>

{% if latest_thought_list %}

    {% for thought in latest_thought_list %}
        <h2>{{  thought.title  }}</h2>
        <p>{{ thought.thought_text }}</p>
    {% endfor %}

{% else %}
    <p>No Thoughts are available.</p>
{% endif %}
<div class="blank-space"></div>
<p class="link"><a href="{% url 'polls:think' %}">Submit a thought?</a></p>
<div class="blank-space"></div>
<footer>
    <p class="foot">Author: Kabir Menghrajani</p>
    <p class="foot"><a href="mailto:km5qte@virginia.edu">km5qte@virginia.edu</a></p>
</footer>
<style>
    body{
        background-color: aquamarine;
    }
    h2, .link{
        color: navy;
        text-align: center;
        font-size: xx-large;
        font-family: 'Akaya Kanadaka', cursive;
    }
    p{
        color: navy;
        text-align: center;
        font-size: large;
        font-family: 'Akaya Kanadaka', cursive;
    }
    .blank-space{
        height: 50px;
    }
    footer, .foot{
        font-size: x-large;
        width: 100%;
    }
</style>